controller:
  enabled: true
scheduling:
  enabled: false

server:
  port: 8092
spring:
  redis:
    port: 6379
    host: localhost
    database: 2
    connect-timeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/staking?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: XCarHikariCP
      max-lifetime: 3600000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      transaction:
        rollback-on-commit-failure: true
      leak-detection-threshold: 3500000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

contracts:
  start: 36261400
  step: 500
  enabled: true
  contractList:
    -
      name: 'StakingManager'
      address: '0x08e64D68959147097DEC69F14f616185194E081F'
      enabled: true
    -
      name: 'NuLinkStakingPool'
      address: '0xE0Ae95b1ce3554358BaFb6ec0abeD89fc4235209'
      enabled: true
    -
      name: 'NuLinkStakingSetting'
      address: '0x8f7F7d0e6300Fce1dd24D0c50292e48f2bB4c2Ad'
      enabled: true
    -
      name: 'NLKFaucet'
      address: '0x60E7980DbA8d4cBaA0C4079801B770cf91311701'
      enabled: true

web3j:
  client-address:
    official: https://data-seed-prebsc-1-s1.bnbchain.org:8545
    ankr: https://rpc.ankr.com/bsc_testnet_chapel/1efbffd5898c6a7f6c352cb46bbee1b70535f3f68a6f00594e123a5b30a99daf
    blockpi: https://bsc-testnet.blockpi.network/v1/rpc/f2599ba0b23571e5510fa6e3d34e6d99c64e04a4
  admin-client: true # to manage accounts, enable the admin client
  httpTimeoutSeconds: 35

knife4j:
  enable: true
  setting:
    language: en-US

NULink:
  porter-service-url: http://8.219.11.39:9165
  password: xxxxxx
  chainId: 97
